# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AQIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Starscream', '~> 4.0.0'
  # Pods for AQIDemo

  target 'AQIDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AQIDemoUITests' do
    # Pods for testing
  end

end
